# Generated by Django 5.0.6 on 2024-06-10 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('operator', models.CharField(max_length=255)),
                ('service_order_code', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(code='invalid_service_order_code', message='O código do pedido de serviço deve estar no formato XXXX-XXXXXX', regex='^\\w{4}-\\w{6}$')])),
                ('creation_datetime', models.DateTimeField()),
                ('user', models.CharField(max_length=255)),
                ('customer', models.CharField(max_length=255)),
                ('priority', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('whatsapp_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
